#!/usr/bin/env python3
"""Generates res/values*/strings.xml for Spin Kingdom.
German (values/) is the default language, English is complete, pl/fr/es translate the
core UI and fall back to English for the rest (every key is present so nothing falls back to German)."""
import os, html

ROOT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

# key: (de, en, {optional: pl, fr, es})
S = {
 "app_name": ("Spin Kingdom", "Spin Kingdom", {}),
 "tagline": ("Drehen. Bauen. Erobern.", "Spin. Build. Conquer.", {"pl": "Kręć. Buduj. Zdobywaj.", "fr": "Tourne. Construis. Conquiers.", "es": "Gira. Construye. Conquista."}),
 "loading": ("Lädt …", "Loading …", {"pl": "Ładowanie …", "fr": "Chargement …", "es": "Cargando …"}),
 "intro1_title": ("Willkommen im Spin Kingdom!", "Welcome to Spin Kingdom!", {"pl": "Witaj w Spin Kingdom!", "fr": "Bienvenue à Spin Kingdom !", "es": "¡Bienvenido a Spin Kingdom!"}),
 "intro1_text": ("Drehe am Glücksrad-Automaten, sammle Münzen und baue dein eigenes Dorf aus – Gebäude für Gebäude.", "Spin the slot machine, collect coins and build up your own village – building by building.", {}),
 "intro2_title": ("Angreifen &amp; Plündern", "Attack &amp; Raid", {"pl": "Atakuj i plądruj", "fr": "Attaque et pille", "es": "Ataca y saquea"}),
 "intro2_text": ("Hämmer schicken dich auf Angriff, Schaufeln zum Überfall. Schilde schützen dein Dorf vor anderen Königen.", "Hammers send you to attack, shovels to raid. Shields protect your village from other kings.", {}),
 "intro3_title": ("Wie heißt du, Majestät?", "What is your name, Your Majesty?", {"pl": "Jak masz na imię, Wasza Wysokość?", "fr": "Quel est ton nom, Majesté ?", "es": "¿Cómo te llamas, Majestad?"}),
 "player_name": ("Spielername", "Player name", {"pl": "Nazwa gracza", "fr": "Nom du joueur", "es": "Nombre del jugador"}),
 "play_as_guest": ("Als Gast spielen", "Play as guest", {"pl": "Graj jako gość", "fr": "Jouer en invité", "es": "Jugar como invitado"}),
 "guest": ("Gast", "Guest", {"pl": "Gość", "fr": "Invité", "es": "Invitado"}),
 "lets_go": ("Los geht\\'s!", "Let\\'s go!", {"pl": "Zaczynamy!", "fr": "C\\'est parti !", "es": "¡Vamos!"}),
 "start_gifts": ("Dein Startgeschenk:", "Your starting gift:", {"pl": "Prezent na start:", "fr": "Ton cadeau de départ :", "es": "Tu regalo inicial:"}),
 "free_spins": ("Gratis-Spins", "free spins", {"pl": "darmowych spinów", "fr": "tours gratuits", "es": "giros gratis"}),
 "next": ("Weiter", "Next", {"pl": "Dalej", "fr": "Suivant", "es": "Siguiente"}),
 "back": ("Zurück", "Back", {"pl": "Wstecz", "fr": "Retour", "es": "Atrás"}),
 "back_to_village": ("Zurück zum Dorf", "Back to village", {"pl": "Wróć do wioski", "fr": "Retour au village", "es": "Volver a la aldea"}),
 "close": ("Schließen", "Close", {"pl": "Zamknij", "fr": "Fermer", "es": "Cerrar"}),
 "cancel": ("Abbrechen", "Cancel", {"pl": "Anuluj", "fr": "Annuler", "es": "Cancelar"}),
 "ok": ("OK", "OK", {}),
 "great": ("Super!", "Great!", {"pl": "Super!", "fr": "Super !", "es": "¡Genial!"}),
 "collect": ("Einsammeln", "Collect", {"pl": "Odbierz", "fr": "Récupérer", "es": "Recoger"}),
 "claim": ("Abholen", "Claim", {"pl": "Odbierz", "fr": "Réclamer", "es": "Reclamar"}),
 "claimed": ("Abgeholt", "Claimed", {"pl": "Odebrano", "fr": "Réclamé", "es": "Reclamado"}),
 "claim_reward": ("Belohnung abholen", "Claim reward", {"pl": "Odbierz nagrodę", "fr": "Réclamer la récompense", "es": "Reclamar recompensa"}),
 "reward": ("Belohnung", "Reward", {"pl": "Nagroda", "fr": "Récompense", "es": "Recompensa"}),
 "reward_title": ("Belohnung erhalten!", "Reward received!", {"pl": "Otrzymano nagrodę!", "fr": "Récompense reçue !", "es": "¡Recompensa recibida!"}),
 "reward_received": ("Belohnung gutgeschrieben", "Reward credited", {}),
 "coins": ("Münzen", "Coins", {"pl": "Monety", "fr": "Pièces", "es": "Monedas"}),
 "spins_short": ("Spins", "spins", {"pl": "spinów", "fr": "tours", "es": "giros"}),
 "stars": ("Sterne", "Stars", {"pl": "Gwiazdy", "fr": "Étoiles", "es": "Estrellas"}),
 "max": ("MAX", "MAX", {}),
 "you": ("Du", "You", {"pl": "Ty", "fr": "Toi", "es": "Tú"}),
 "level_n": ("Level %1$d", "Level %1$d", {"pl": "Poziom %1$d", "fr": "Niveau %1$d", "es": "Nivel %1$d"}),
 "level_title": ("Level %1$d · %2$s", "Level %1$d · %2$s", {"pl": "Poziom %1$d · %2$s", "fr": "Niveau %1$d · %2$s", "es": "Nivel %1$d · %2$s"}),
 "menu": ("Menü", "Menu", {"pl": "Menu", "fr": "Menu", "es": "Menú"}),
 "menu_profile": ("Profil", "Profile", {"pl": "Profil", "fr": "Profil", "es": "Perfil"}),
 "menu_shop": ("Shop", "Shop", {"pl": "Sklep", "fr": "Boutique", "es": "Tienda"}),
 "menu_daily": ("Tagesbonus", "Daily bonus", {"pl": "Bonus dzienny", "fr": "Bonus quotidien", "es": "Bono diario"}),
 "menu_wheel": ("Glücksrad", "Lucky wheel", {"pl": "Koło fortuny", "fr": "Roue de la fortune", "es": "Rueda de la suerte"}),
 "menu_missions": ("Missionen", "Missions", {"pl": "Misje", "fr": "Missions", "es": "Misiones"}),
 "menu_pets": ("Haustiere", "Pets", {"pl": "Zwierzaki", "fr": "Familiers", "es": "Mascotas"}),
 "menu_cards": ("Karten", "Cards", {"pl": "Karty", "fr": "Cartes", "es": "Cartas"}),
 "menu_leaderboard": ("Rangliste", "Leaderboard", {"pl": "Ranking", "fr": "Classement", "es": "Clasificación"}),
 "menu_settings": ("Einstellungen", "Settings", {"pl": "Ustawienia", "fr": "Paramètres", "es": "Ajustes"}),
 "spin_button": ("DREHEN", "SPIN", {"pl": "KRĘĆ", "fr": "TOURNER", "es": "GIRAR"}),
 "spinning": ("Dreht …", "Spinning …", {"pl": "Kręci się …", "fr": "Ça tourne …", "es": "Girando …"}),
 "next_spin_in": ("+%1$d Spins in %2$s", "+%1$d spins in %2$s", {"pl": "+%1$d spinów za %2$s", "fr": "+%1$d tours dans %2$s", "es": "+%1$d giros en %2$s"}),
 "spins_full": ("Spins voll aufgeladen", "Spins fully charged", {"pl": "Spiny w pełni naładowane", "fr": "Tours rechargés", "es": "Giros al máximo"}),
 "build": ("BAUEN", "BUILD", {"pl": "BUDUJ", "fr": "BÂTIR", "es": "CONSTRUIR"}),
 "build_title": ("Dorf ausbauen", "Build your village", {"pl": "Rozbuduj wioskę", "fr": "Agrandir le village", "es": "Mejora tu aldea"}),
 "damaged": ("Beschädigt – reparieren", "Damaged – repair", {"pl": "Uszkodzony – napraw", "fr": "Endommagé – réparer", "es": "Dañado – reparar"}),
 "to_next_village": ("Zum nächsten Dorf", "To the next village", {"pl": "Do następnej wioski", "fr": "Vers le prochain village", "es": "A la siguiente aldea"}),
 "next_village": ("Nächstes Dorf: %1$s", "Next village: %1$s", {"pl": "Następna wioska: %1$s", "fr": "Prochain village : %1$s", "es": "Siguiente aldea: %1$s"}),
 "village_complete": ("Dorf vollendet!", "Village complete!", {"pl": "Wioska ukończona!", "fr": "Village terminé !", "es": "¡Aldea completada!"}),
 "village_complete_text": ("%1$s erstrahlt in vollem Glanz. Das nächste Abenteuer wartet!", "%1$s shines in full glory. The next adventure awaits!", {}),
 "big_win": ("Großer Gewinn!", "Big win!", {"pl": "Wielka wygrana!", "fr": "Gros gain !", "es": "¡Gran premio!"}),
 "jackpot": ("JACKPOT!", "JACKPOT!", {}),
 "spin_bonus": ("Energie-Bonus!", "Energy bonus!", {"pl": "Bonus energii!", "fr": "Bonus d\\'énergie !", "es": "¡Bono de energía!"}),
 "attack_title": ("Angriff!", "Attack!", {"pl": "Atak!", "fr": "Attaque !", "es": "¡Ataque!"}),
 "attack_ready": ("Angriff bereit – tippe hier!", "Attack ready – tap here!", {"pl": "Atak gotowy – dotknij!", "fr": "Attaque prête – touche ici !", "es": "¡Ataque listo – toca aquí!"}),
 "next_attack": ("Nächster Angriff", "Next attack", {"pl": "Następny atak", "fr": "Attaque suivante", "es": "Siguiente ataque"}),
 "choose_building": ("Wähle ein Gebäude zum Angreifen", "Choose a building to attack", {"pl": "Wybierz budynek do ataku", "fr": "Choisis un bâtiment à attaquer", "es": "Elige un edificio para atacar"}),
 "firing": ("Feuer!", "Fire!", {"pl": "Ognia!", "fr": "Feu !", "es": "¡Fuego!"}),
 "attack_success": ("Volltreffer!", "Direct hit!", {"pl": "Trafienie!", "fr": "En plein dans le mille !", "es": "¡Impacto directo!"}),
 "attack_success_text": ("Du hast das Dorf von %1$s getroffen und Beute gemacht.", "You hit %1$s\\'s village and grabbed loot.", {}),
 "attack_blocked": ("Geblockt!", "Blocked!", {"pl": "Zablokowano!", "fr": "Bloqué !", "es": "¡Bloqueado!"}),
 "attack_blocked_text": ("Ein Schild hat den Angriff abgewehrt. Du erhältst einen Trostpreis.", "A shield blocked the attack. You get a consolation prize.", {}),
 "no_attack_pending": ("Kein Angriff verfügbar. Drehe drei Hämmer, um anzugreifen!", "No attack available. Spin three hammers to attack!", {}),
 "searching_opponent": ("Suche Gegner …", "Searching opponent …", {"pl": "Szukam przeciwnika …", "fr": "Recherche d\\'un adversaire …", "es": "Buscando rival …"}),
 "raid_title": ("Überfall!", "Raid!", {"pl": "Napad!", "fr": "Pillage !", "es": "¡Saqueo!"}),
 "raid_ready": ("Überfall bereit – tippe hier!", "Raid ready – tap here!", {"pl": "Napad gotowy – dotknij!", "fr": "Pillage prêt – touche ici !", "es": "¡Saqueo listo – toca aquí!"}),
 "raid_pick": ("Grabe! Noch %1$d Versuche", "Dig! %1$d tries left", {"pl": "Kop! Pozostało prób: %1$d", "fr": "Creuse ! Encore %1$d essais", "es": "¡Excava! Quedan %1$d intentos"}),
 "raid_finished": ("Überfall beendet!", "Raid finished!", {"pl": "Napad zakończony!", "fr": "Pillage terminé !", "es": "¡Saqueo terminado!"}),
 "raid_loot": ("Deine Beute", "Your loot", {"pl": "Twój łup", "fr": "Ton butin", "es": "Tu botín"}),
 "no_raid_pending": ("Kein Überfall verfügbar. Drehe drei Schaufeln für einen Überfall!", "No raid available. Spin three shovels to raid!", {}),
 "while_away": ("Während du weg warst …", "While you were away …", {"pl": "Gdy cię nie było …", "fr": "Pendant ton absence …", "es": "Mientras no estabas …"}),
 "log_blocked": ("%1$s hat angegriffen – dein Schild hat gehalten!", "%1$s attacked – your shield held!", {}),
 "log_hit": ("%1$s hat eines deiner Gebäude beschädigt.", "%1$s damaged one of your buildings.", {}),
 "chest_wood": ("Holztruhe", "Wooden chest", {"pl": "Drewniana skrzynia", "fr": "Coffre en bois", "es": "Cofre de madera"}),
 "chest_silver": ("Silbertruhe", "Silver chest", {"pl": "Srebrna skrzynia", "fr": "Coffre d\\'argent", "es": "Cofre de plata"}),
 "chest_gold": ("Goldtruhe", "Gold chest", {"pl": "Złota skrzynia", "fr": "Coffre d\\'or", "es": "Cofre de oro"}),
 "chest_royal": ("Königstruhe", "Royal chest", {"pl": "Królewska skrzynia", "fr": "Coffre royal", "es": "Cofre real"}),
 "chest_legendary": ("Legendäre Truhe", "Legendary chest", {"pl": "Legendarna skrzynia", "fr": "Coffre légendaire", "es": "Cofre legendario"}),
 "new_card": ("NEU", "NEW", {"pl": "NOWA", "fr": "NOUV.", "es": "NUEVA"}),
 "card_album": ("Kartenalbum", "Card album", {"pl": "Album kart", "fr": "Album de cartes", "es": "Álbum de cartas"}),
 "rarity_common": ("Gewöhnlich", "Common", {"pl": "Zwykła", "fr": "Commune", "es": "Común"}),
 "rarity_rare": ("Selten", "Rare", {"pl": "Rzadka", "fr": "Rare", "es": "Rara"}),
 "rarity_epic": ("Episch", "Epic", {"pl": "Epicka", "fr": "Épique", "es": "Épica"}),
 "rarity_legendary": ("Legendär", "Legendary", {"pl": "Legendarna", "fr": "Légendaire", "es": "Legendaria"}),
 "owned_times": ("×%1$d", "×%1$d", {}),
 "set_reward": ("Belohnung für das komplette Set", "Reward for the complete set", {}),
 "set_complete": ("Set komplett!", "Set complete!", {"pl": "Zestaw ukończony!", "fr": "Collection complète !", "es": "¡Colección completa!"}),
 "set_complete_text": ("Du hast alle Karten dieses Sets gesammelt.", "You collected all cards of this set.", {}),
 "set_unlocks_at": ("Freigeschaltet ab Level %1$d", "Unlocks at level %1$d", {"pl": "Odblokowanie na poziomie %1$d", "fr": "Débloqué au niveau %1$d", "es": "Se desbloquea en el nivel %1$d"}),
 "unlocks_at_level": ("Ab Level %1$d", "From level %1$d", {"pl": "Od poziomu %1$d", "fr": "Dès le niveau %1$d", "es": "Desde el nivel %1$d"}),
 "set_0": ("Königshof", "Royal Court", {}),
 "set_1": ("Seefahrer", "Seafarers", {}),
 "set_2": ("Fabelwesen", "Mythical Beasts", {}),
 "set_3": ("Schatzkammer", "Treasury", {}),
 "set_4": ("Entdecker", "Explorers", {}),
 "set_5": ("Magie &amp; Sterne", "Magic &amp; Stars", {}),
 "pet_fox": ("Fuchs", "Fox", {"pl": "Lis", "fr": "Renard", "es": "Zorro"}),
 "pet_dragon": ("Drache", "Dragon", {"pl": "Smok", "fr": "Dragon", "es": "Dragón"}),
 "pet_raccoon": ("Waschbär", "Raccoon", {"pl": "Szop", "fr": "Raton laveur", "es": "Mapache"}),
 "pet_phoenix": ("Phönix", "Phoenix", {"pl": "Feniks", "fr": "Phénix", "es": "Fénix"}),
 "pet_fox_desc": ("Der schlaue Fuchs erschnüffelt bei Überfällen mehr Beute.", "The clever fox sniffs out more loot during raids.", {}),
 "pet_dragon_desc": ("Der Drache verstärkt deine Angriffe mit Feueratem.", "The dragon boosts your attacks with fire breath.", {}),
 "pet_raccoon_desc": ("Der Waschbär findet bei jedem Münzgewinn noch ein paar extra Münzen.", "The raccoon finds some extra coins on every coin win.", {}),
 "pet_phoenix_desc": ("Der Phönix schenkt dir manchmal einen Spin zurück.", "The phoenix sometimes gives you a spin back.", {}),
 "pet_fox_effect": ("+%1$d %% Überfallbeute", "+%1$d %% raid loot", {}),
 "pet_dragon_effect": ("+%1$d %% Angriffsbeute", "+%1$d %% attack loot", {}),
 "pet_raccoon_effect": ("+%1$d %% Münzgewinne", "+%1$d %% coin wins", {}),
 "pet_phoenix_effect": ("%1$d %% Chance auf Gratis-Spin", "%1$d %% chance of a free spin", {}),
 "pet_level_up": ("Haustier-Level-Up!", "Pet level up!", {"pl": "Zwierzak awansował!", "fr": "Familier niveau supérieur !", "es": "¡Mascota sube de nivel!"}),
 "pet_level_up_text": ("%1$s ist stärker geworden!", "%1$s got stronger!", {}),
 "feed": ("Füttern", "Feed", {"pl": "Nakarm", "fr": "Nourrir", "es": "Alimentar"}),
 "treats": ("Leckerlis", "treats", {"pl": "przysmaki", "fr": "friandises", "es": "golosinas"}),
 "treat_hint": ("Jedes Leckerli gibt %1$d XP. Leckerlis gibt es in Truhen und am Glücksrad.", "Each treat gives %1$d XP. Treats come from chests and the lucky wheel.", {}),
 "active": ("Aktiv", "Active", {"pl": "Aktywny", "fr": "Actif", "es": "Activo"}),
 "activate": ("Aktivieren", "Activate", {"pl": "Aktywuj", "fr": "Activer", "es": "Activar"}),
 "daily": ("Täglich", "Daily", {"pl": "Dzienne", "fr": "Quotidien", "es": "Diarias"}),
 "weekly": ("Wöchentlich", "Weekly", {"pl": "Tygodniowe", "fr": "Hebdo", "es": "Semanales"}),
 "day_n": ("Tag %1$d", "Day %1$d", {"pl": "Dzień %1$d", "fr": "Jour %1$d", "es": "Día %1$d"}),
 "daily_title": ("Tagesbonus!", "Daily bonus!", {"pl": "Bonus dzienny!", "fr": "Bonus quotidien !", "es": "¡Bono diario!"}),
 "daily_sub": ("Komm jeden Tag vorbei – am 7. Tag wartet der Jackpot!", "Come back every day – the jackpot waits on day 7!", {}),
 "daily_rule": ("Verpasst du einen Tag, beginnt die Serie wieder bei Tag 1.", "Miss a day and the streak restarts at day 1.", {}),
 "come_back_in": ("Nächster Bonus in %1$s", "Next bonus in %1$s", {"pl": "Następny bonus za %1$s", "fr": "Prochain bonus dans %1$s", "es": "Próximo bono en %1$s"}),
 "wheel_title": ("Glücksrad-Gewinn!", "Lucky wheel prize!", {}),
 "wheel_sub": ("Einmal täglich gratis drehen!", "Spin once a day for free!", {"pl": "Kręć raz dziennie za darmo!", "fr": "Tourne gratuitement une fois par jour !", "es": "¡Gira gratis una vez al día!"}),
 "spin_free": ("Gratis drehen", "Spin for free", {"pl": "Kręć za darmo", "fr": "Tourner gratuitement", "es": "Girar gratis"}),
 "next_free_spin": ("Nächster Gratis-Dreh in %1$s", "Next free spin in %1$s", {}),
 "err_clock": ("Die Geräteuhr wurde zurückgestellt. Tagesbelohnungen sind erst wieder verfügbar, wenn die Zeit stimmt.", "The device clock was set back. Daily rewards are available again once the time is correct.", {}),
 "mission_spins": ("Drehe %1$d-mal", "Spin %1$d times", {"pl": "Zakręć %1$d razy", "fr": "Tourne %1$d fois", "es": "Gira %1$d veces"}),
 "mission_attacks": ("Führe %1$d Angriffe aus", "Make %1$d attacks", {"pl": "Wykonaj %1$d ataki", "fr": "Fais %1$d attaques", "es": "Haz %1$d ataques"}),
 "mission_raids": ("Führe %1$d Überfälle aus", "Make %1$d raids", {"pl": "Wykonaj %1$d napady", "fr": "Fais %1$d pillages", "es": "Haz %1$d saqueos"}),
 "mission_upgrades": ("Baue %1$d Gebäudestufen aus", "Build %1$d building upgrades", {}),
 "mission_coins": ("Sammle %1$s Münzen", "Collect %1$s coins", {"pl": "Zbierz %1$s monet", "fr": "Récolte %1$s pièces", "es": "Recoge %1$s monedas"}),
 "mission_chests": ("Öffne %1$d Truhen", "Open %1$d chests", {"pl": "Otwórz %1$d skrzynie", "fr": "Ouvre %1$d coffres", "es": "Abre %1$d cofres"}),
 "mission_shields": ("Erhalte %1$d Schilde", "Win %1$d shields", {}),
 "mission_reward": ("Mission erfüllt!", "Mission complete!", {"pl": "Misja wykonana!", "fr": "Mission accomplie !", "es": "¡Misión cumplida!"}),
 "resets_in": ("Neue Missionen in %1$s", "New missions in %1$s", {"pl": "Nowe misje za %1$s", "fr": "Nouvelles missions dans %1$s", "es": "Nuevas misiones en %1$s"}),
 "leaderboard_sub": ("Offline-Rangliste – bald auch mit echten Spielern", "Offline ranking – real players coming later", {}),
 "your_rank": ("Dein Rang: #%1$d", "Your rank: #%1$d", {"pl": "Twoje miejsce: #%1$d", "fr": "Ton rang : #%1$d", "es": "Tu puesto: #%1$d"}),
 "statistics": ("Statistiken", "Statistics", {"pl": "Statystyki", "fr": "Statistiques", "es": "Estadísticas"}),
 "stat_attacks_won": ("Gewonnene Angriffe", "Attacks won", {}),
 "stat_attacks_blocked": ("Abgewehrte Angriffe", "Attacks blocked", {}),
 "stat_raids": ("Überfälle", "Raids", {}),
 "stat_cards": ("Gesammelte Karten", "Cards collected", {}),
 "stat_spins": ("Spins gesamt", "Total spins", {}),
 "stat_jackpots": ("Jackpots", "Jackpots", {}),
 "stat_chests": ("Geöffnete Truhen", "Chests opened", {}),
 "stat_upgrades": ("Gebäude-Ausbauten", "Building upgrades", {}),
 "stat_levels": ("Vollendete Dörfer", "Villages completed", {}),
 "stat_coins_earned": ("Münzen verdient", "Coins earned", {}),
 "stat_biggest_win": ("Größter Gewinn", "Biggest win", {}),
 "shop_spins": ("Spins", "Spins", {"pl": "Spiny", "fr": "Tours", "es": "Giros"}),
 "shop_coins": ("Münzen", "Coins", {"pl": "Monety", "fr": "Pièces", "es": "Monedas"}),
 "shop_chests": ("Truhen", "Chests", {"pl": "Skrzynie", "fr": "Coffres", "es": "Cofres"}),
 "shop_offers": ("Angebote", "Offers", {"pl": "Oferty", "fr": "Offres", "es": "Ofertas"}),
 "shop_test_banner": ("TESTMODUS: Alle Käufe sind Testkäufe – es wird kein echtes Geld abgebucht.", "TEST MODE: All purchases are test purchases – no real money is charged.", {}),
 "shop_footer": ("Später über Google Play Billing verfügbar. Aktuell nur simulierte Testkäufe.", "Later available through Google Play Billing. Currently simulated test purchases only.", {}),
 "test_purchase": ("Testkauf", "Test purchase", {"pl": "Zakup testowy", "fr": "Achat test", "es": "Compra de prueba"}),
 "confirm_test_purchase": ("Testkauf bestätigen? Es wird kein echtes Geld verwendet.", "Confirm test purchase? No real money is used.", {}),
 "no_real_money": ("Kein echtes Geld", "No real money", {"pl": "Bez prawdziwych pieniędzy", "fr": "Pas d\\'argent réel", "es": "Sin dinero real"}),
 "shop_test_success": ("Testkauf erfolgreich!", "Test purchase successful!", {}),
 "shop_failed": ("Kauf fehlgeschlagen", "Purchase failed", {}),
 "p_offer_starter": ("Starterpaket", "Starter pack", {}),
 "p_offer_king": ("Königspaket", "King\\'s pack", {}),
 "p_spins_small": ("Handvoll Spins", "Handful of spins", {}),
 "p_spins_medium": ("Spin-Beutel", "Bag of spins", {}),
 "p_spins_large": ("Spin-Truhe", "Chest of spins", {}),
 "p_coins_small": ("Münzstapel", "Stack of coins", {}),
 "p_coins_large": ("Münzberg", "Mountain of coins", {}),
 "p_chest_gold": ("Goldtruhe", "Gold chest", {}),
 "p_chest_royal": ("Königstruhe", "Royal chest", {}),
 "p_chest_legendary": ("Legendäre Truhe", "Legendary chest", {}),
 "watch": ("Ansehen", "Watch", {"pl": "Oglądaj", "fr": "Regarder", "es": "Ver"}),
 "watch_ad_for_spins": ("Werbung ansehen und %1$d Spins erhalten", "Watch an ad and get %1$d spins", {"pl": "Obejrzyj reklamę i zdobądź %1$d spinów", "fr": "Regarde une pub et gagne %1$d tours", "es": "Mira un anuncio y consigue %1$d giros"}),
 "double_reward": ("Belohnung verdoppeln", "Double reward", {"pl": "Podwój nagrodę", "fr": "Doubler la récompense", "es": "Duplicar recompensa"}),
 "ad_short": ("+Spins", "+Spins", {}),
 "ad_simulated": ("Simulierte Werbung (Test)", "Simulated ad (test)", {}),
 "ad_fake_title": ("Spin Kingdom – bald mit echten Werbepartnern", "Spin Kingdom – real ad partners coming later", {}),
 "ad_seconds_left": ("Belohnung in %1$d s", "Reward in %1$d s", {}),
 "ad_skip_no_reward": ("Abbrechen (keine Belohnung)", "Cancel (no reward)", {}),
 "ad_collect_reward": ("Belohnung abholen", "Collect reward", {}),
 "ad_cancelled": ("Werbung abgebrochen – keine Belohnung", "Ad cancelled – no reward", {}),
 "audio_and_feel": ("Ton &amp; Gefühl", "Sound &amp; feel", {"pl": "Dźwięk i wibracje", "fr": "Son et sensations", "es": "Sonido y sensación"}),
 "music": ("Musik", "Music", {"pl": "Muzyka", "fr": "Musique", "es": "Música"}),
 "sound_effects": ("Soundeffekte", "Sound effects", {"pl": "Efekty dźwiękowe", "fr": "Effets sonores", "es": "Efectos de sonido"}),
 "vibration": ("Vibration", "Vibration", {"pl": "Wibracje", "fr": "Vibration", "es": "Vibración"}),
 "notifications": ("Benachrichtigungen", "Notifications", {"pl": "Powiadomienia", "fr": "Notifications", "es": "Notificaciones"}),
 "notifications_hint": ("Erinnerung, wenn deine Spins wieder voll sind", "Reminder when your spins are full again", {}),
 "language": ("Sprache", "Language", {"pl": "Język", "fr": "Langue", "es": "Idioma"}),
 "privacy": ("Datenschutz", "Privacy", {"pl": "Prywatność", "fr": "Confidentialité", "es": "Privacidad"}),
 "privacy_text": ("Spin Kingdom funktioniert komplett offline. Es werden keine persönlichen Daten erhoben, an Server gesendet oder mit Dritten geteilt. Dein Spielstand wird ausschließlich lokal auf diesem Gerät gespeichert. Es gibt keine echte Werbung, kein Tracking und keine echten Käufe – Shop und Werbung sind Simulationen. Die App benötigt nur die Berechtigungen für Vibration und (optional) Benachrichtigungen.", "Spin Kingdom works completely offline. No personal data is collected, sent to servers or shared with third parties. Your save game is stored only locally on this device. There is no real advertising, no tracking and no real purchases – shop and ads are simulations. The app only needs the permissions for vibration and (optionally) notifications.", {}),
 "savegame": ("Spielstand", "Save game", {"pl": "Zapis gry", "fr": "Sauvegarde", "es": "Partida guardada"}),
 "save": ("Speichern", "Save", {"pl": "Zapisz", "fr": "Enregistrer", "es": "Guardar"}),
 "save_location": ("Speicherort", "Location", {}),
 "save_location_value": ("Lokal auf dem Gerät (DataStore)", "Local on device (DataStore)", {}),
 "started_on": ("Gestartet am", "Started on", {"pl": "Rozpoczęto", "fr": "Commencé le", "es": "Iniciado el"}),
 "player_id": ("Spieler-ID", "Player ID", {"pl": "ID gracza", "fr": "ID joueur", "es": "ID de jugador"}),
 "version": ("Version %1$s (%2$d)", "Version %1$s (%2$d)", {"pl": "Wersja %1$s (%2$d)", "fr": "Version %1$s (%2$d)", "es": "Versión %1$s (%2$d)"}),
 "reset": ("Zurücksetzen", "Reset", {"pl": "Resetuj", "fr": "Réinitialiser", "es": "Restablecer"}),
 "reset_game": ("Spielstand zurücksetzen", "Reset save game", {"pl": "Resetuj zapis gry", "fr": "Réinitialiser la partie", "es": "Borrar partida"}),
 "reset_confirm": ("Willst du wirklich von vorne beginnen? Dein gesamter Fortschritt geht verloren.", "Do you really want to start over? All your progress will be lost.", {}),
 "notif_channel": ("Spin-Erinnerungen", "Spin reminders", {"pl": "Przypomnienia o spinach", "fr": "Rappels de tours", "es": "Recordatorios de giros"}),
 "notif_title": ("Deine Spins sind voll!", "Your spins are full!", {"pl": "Twoje spiny są pełne!", "fr": "Tes tours sont pleins !", "es": "¡Tus giros están llenos!"}),
 "notif_text": ("Dein Königreich wartet – komm zurück und dreh los!", "Your kingdom awaits – come back and spin!", {}),
 "err_no_spins": ("Nicht genug Spins!", "Not enough spins!", {"pl": "Za mało spinów!", "fr": "Pas assez de tours !", "es": "¡No hay giros suficientes!"}),
 "err_no_coins": ("Nicht genug Münzen!", "Not enough coins!", {"pl": "Za mało monet!", "fr": "Pas assez de pièces !", "es": "¡No hay monedas suficientes!"}),
 "err_max_stage": ("Bereits voll ausgebaut", "Already fully upgraded", {}),
 "err_already_claimed": ("Bereits abgeholt", "Already claimed", {"pl": "Już odebrano", "fr": "Déjà réclamé", "es": "Ya reclamado"}),
 "err_not_available": ("Nicht verfügbar", "Not available", {"pl": "Niedostępne", "fr": "Indisponible", "es": "No disponible"}),
 "err_no_treats": ("Keine Leckerlis übrig", "No treats left", {}),
 "event_pirates": ("Piraten-Event", "Pirate event", {}),
 "event_halloween": ("Halloween", "Halloween", {}),
 "event_christmas": ("Weihnachten", "Christmas", {"pl": "Boże Narodzenie", "fr": "Noël", "es": "Navidad"}),
 "event_summer": ("Sommerfest", "Summer festival", {}),
 "event_treasure": ("Schatzsuche", "Treasure hunt", {"pl": "Poszukiwanie skarbów", "fr": "Chasse au trésor", "es": "Búsqueda del tesoro"}),
 "event_double_coins": ("Doppel-Münzen-Tag", "Double coins day", {}),
 "event_bonus_spins": ("Bonus-Spins-Woche", "Bonus spins week", {}),
 "event_generic": ("Sonder-Event", "Special event", {}),
 "event_bonus_coins": ("Münzen ×%1$s", "Coins ×%1$s", {}),
 "event_bonus_spins_x": ("Spins ×%1$s", "Spins ×%1$s", {}),
 "event_bonus_raid": ("Überfall ×%1$s", "Raid ×%1$s", {}),
 "event_bonus_attack": ("Angriff ×%1$s", "Attack ×%1$s", {}),
 "event_bonus_chest": ("Bessere Truhen", "Better chests", {}),
 "debug_menu": ("Debug-Menü", "Debug menu", {}),
 "debug_hint": ("Nur zum Testen. Über BuildConfig.DEBUG_MENU_ENABLED abschaltbar.", "For testing only. Can be disabled via BuildConfig.DEBUG_MENU_ENABLED.", {}),
 "debug_coins": ("+ Münzen (ein ganzes Dorf)", "+ Coins (a whole village)", {}),
 "debug_spins": ("+500 Spins", "+500 spins", {}),
 "debug_shields": ("Schilde auffüllen", "Fill shields", {}),
 "debug_level": ("Level: %1$d", "Level: %1$d", {}),
 "debug_set_level": ("Level setzen", "Set level", {}),
 "debug_finish_buildings": ("Alle Gebäude fertigstellen", "Finish all buildings", {}),
 "debug_complete_level": ("Dorf abschließen", "Complete village", {}),
 "debug_cards": ("Alle Karten freischalten", "Unlock all cards", {}),
 "debug_chests": ("Königstruhe erhalten", "Get royal chest", {}),
 "debug_treats": ("+20 Leckerlis &amp; alle Haustiere", "+20 treats &amp; all pets", {}),
 "debug_attack": ("Angriff auslösen", "Trigger attack", {}),
 "debug_raid": ("Überfall auslösen", "Trigger raid", {}),
 "debug_bot_attack": ("Bot-Angriff simulieren", "Simulate bot attack", {}),
 "debug_damage": ("Gebäude beschädigen", "Damage a building", {}),
 "debug_reset_daily": ("Tagesbonus/Glücksrad zurücksetzen", "Reset daily bonus/wheel", {}),
 "debug_events": ("Aktive Events", "Active events", {}),
}

THEMES_DE = ["Kleines Königreich", "Pirateninsel", "Wikinger-Dorf", "Wilder Westen", "Dschungel", "Ägypten", "Eiswelt", "Zauberwald", "Unterwasserwelt", "Weltraum", "Drachenland", "Samurai-Dorf", "Süßigkeitenwelt", "Dinosaurierwelt", "Geisterstadt", "Mittelalter", "Vulkaninsel", "Märchenwelt", "Roboterstadt", "Wolkenreich", "Wüstenoase", "Blütental", "Kristallhöhle", "Steampunk-Stadt", "Zirkuswelt", "Atlantis", "Olymp", "Nordlicht-Tundra", "Pilzland", "Goldene Stadt"]
THEMES_EN = ["Little Kingdom", "Pirate Island", "Viking Village", "Wild West", "Jungle", "Egypt", "Ice World", "Enchanted Forest", "Underwater World", "Outer Space", "Dragon Land", "Samurai Village", "Candy World", "Dinosaur World", "Ghost Town", "Middle Ages", "Volcano Island", "Fairy Tale World", "Robot City", "Cloud Kingdom", "Desert Oasis", "Blossom Valley", "Crystal Cave", "Steampunk City", "Circus World", "Atlantis", "Olympus", "Aurora Tundra", "Mushroom Land", "Golden City"]
for i in range(30):
    S[f"theme_{i}"] = (THEMES_DE[i], THEMES_EN[i], {})

BUILD_DE = [
 ["Bauernhaus", "Windmühle", "Marktstand", "Wachturm", "Königsburg"],
 ["Strandhütte", "Piratenzelt", "Piratenschiff", "Leuchtturm", "Ausguck"],
 ["Langhaus", "Runenstein", "Drachenboot", "Wachturm", "Jarlshalle"],
 ["Planwagen", "Saloon", "Wasserpumpe", "Sheriffturm", "Goldgräberstatue"],
 ["Bambushütte", "Baumhaus", "Götzenbild", "Lianenturm", "Tempelpyramide"],
 ["Beduinenzelt", "Kuppelgrab", "Obelisk", "Sphinx", "Große Pyramide"],
 ["Iglu", "Eiskuppel", "Eisbär-Statue", "Frostturm", "Eispalast"],
 ["Hexenhaus", "Zauberkuppel", "Elfenbaumhaus", "Einhornstatue", "Magierturm"],
 ["Muschelkuppel", "Meerjungfrau", "Schiffswrack", "Korallenturm", "Poseidons Palast"],
 ["Mondbasis", "Astronauten-Denkmal", "Funkturm", "Rakete", "Sternenfestung"],
 ["Drachenhort", "Lavakuppel", "Drachenstatue", "Feuerturm", "Drachenburg"],
 ["Teehaus", "Dojo-Zelt", "Buddha-Statue", "Wachturm", "Pagode"],
 ["Lebkuchenhaus", "Zuckerzelt", "Bonbonkuppel", "Lolli-Statue", "Schokoturm"],
 ["Höhle", "Baumnest", "Eierkuppel", "T-Rex-Skelett", "Vulkanturm"],
 ["Spukhaus", "Geistermühle", "Grabstein", "Glockenturm", "Gruselschloss"],
 ["Fachwerkhaus", "Ritterzelt", "Mühle", "Burgfried", "Ritterburg"],
 ["Lavahütte", "Magmakuppel", "Feuergötze", "Aschenturm", "Feuerpyramide"],
 ["Knusperhaus", "Feenbaum", "Froschkönig", "Rapunzelturm", "Märchenschloss"],
 ["Werkstatt-Kuppel", "Roboter-Statue", "Antennenturm", "Raketenstart", "Mecha-Zitadelle"],
 ["Wolkenkuppel", "Windrad", "Engelsstatue", "Himmelsturm", "Wolkenschloss"],
 ["Nomadenzelt", "Oasenkuppel", "Kamelstatue", "Minarett", "Sandpyramide"],
 ["Blütenhaus", "Gartenzelt", "Blumenmühle", "Blütenbaumhaus", "Schmetterlingsstatue"],
 ["Kristallkuppel", "Geodenstatue", "Kristallturm", "Juwelpyramide", "Kristallpalast"],
 ["Zahnradhaus", "Dampfmühle", "Luftschiffhafen", "Uhrenturm", "Dampfrakete"],
 ["Zirkuszelt", "Wohnwagen", "Manege", "Clownstatue", "Akrobatenturm"],
 ["Perlenkuppel", "Tritonstatue", "Säulenturm", "Tempelpyramide", "Atlantis-Palast"],
 ["Götterstatue", "Tempelkuppel", "Säulenturm", "Ruhmespyramide", "Zeus-Palast"],
 ["Jurte", "Schneekuppel", "Rentierstatue", "Polarturm", "Polarlicht-Leuchtturm"],
 ["Pilzkuppel", "Pilzhaus", "Pilzbaumhaus", "Schneckenstatue", "Pilzturm"],
 ["Goldstatue", "Goldkuppel", "Goldturm", "Goldpyramide", "Goldpalast"],
]
BUILD_EN = [
 ["Farmhouse", "Windmill", "Market stall", "Watchtower", "Royal castle"],
 ["Beach hut", "Pirate tent", "Pirate ship", "Lighthouse", "Lookout"],
 ["Longhouse", "Rune stone", "Dragon boat", "Watchtower", "Jarl\\'s hall"],
 ["Covered wagon", "Saloon", "Water pump", "Sheriff tower", "Prospector statue"],
 ["Bamboo hut", "Treehouse", "Idol", "Vine tower", "Temple pyramid"],
 ["Bedouin tent", "Domed tomb", "Obelisk", "Sphinx", "Great pyramid"],
 ["Igloo", "Ice dome", "Polar bear statue", "Frost tower", "Ice palace"],
 ["Witch\\'s house", "Magic dome", "Elven treehouse", "Unicorn statue", "Wizard tower"],
 ["Shell dome", "Mermaid", "Shipwreck", "Coral tower", "Poseidon\\'s palace"],
 ["Moon base", "Astronaut monument", "Radio tower", "Rocket", "Star fortress"],
 ["Dragon lair", "Lava dome", "Dragon statue", "Fire tower", "Dragon castle"],
 ["Tea house", "Dojo tent", "Buddha statue", "Watchtower", "Pagoda"],
 ["Gingerbread house", "Sugar tent", "Candy dome", "Lollipop statue", "Chocolate tower"],
 ["Cave", "Tree nest", "Egg dome", "T-Rex skeleton", "Volcano tower"],
 ["Haunted house", "Ghost mill", "Tombstone", "Bell tower", "Spooky castle"],
 ["Timber house", "Knight tent", "Mill", "Keep", "Knight castle"],
 ["Lava hut", "Magma dome", "Fire idol", "Ash tower", "Fire pyramid"],
 ["Candy cottage", "Fairy tree", "Frog prince", "Rapunzel tower", "Fairy tale castle"],
 ["Workshop dome", "Robot statue", "Antenna tower", "Rocket launch", "Mecha citadel"],
 ["Cloud dome", "Wind wheel", "Angel statue", "Sky tower", "Cloud castle"],
 ["Nomad tent", "Oasis dome", "Camel statue", "Minaret", "Sand pyramid"],
 ["Blossom house", "Garden tent", "Flower mill", "Blossom treehouse", "Butterfly statue"],
 ["Crystal dome", "Geode statue", "Crystal tower", "Jewel pyramid", "Crystal palace"],
 ["Cog house", "Steam mill", "Airship dock", "Clock tower", "Steam rocket"],
 ["Big top", "Caravan", "Ring", "Clown statue", "Acrobat tower"],
 ["Pearl dome", "Triton statue", "Column tower", "Temple pyramid", "Atlantis palace"],
 ["God statue", "Temple dome", "Column tower", "Pyramid of glory", "Zeus\\'s palace"],
 ["Yurt", "Snow dome", "Reindeer statue", "Polar tower", "Aurora lighthouse"],
 ["Mushroom dome", "Mushroom house", "Mushroom treehouse", "Snail statue", "Mushroom tower"],
 ["Gold statue", "Gold dome", "Gold tower", "Gold pyramid", "Gold palace"],
]
STAGES_DE = ["Bauplatz", "Fundament", "Einfach", "Ausgebaut", "Prächtig", "Legendär"]
STAGES_EN = ["Building site", "Foundation", "Simple", "Improved", "Splendid", "Legendary"]
STAGES_X = {"pl": ["Plac budowy", "Fundament", "Prosty", "Ulepszony", "Wspaniały", "Legendarny"],
            "fr": ["Chantier", "Fondations", "Simple", "Amélioré", "Splendide", "Légendaire"],
            "es": ["Solar", "Cimientos", "Sencillo", "Mejorado", "Espléndido", "Legendario"]}
CARDS_DE = [
 ["Bauer", "Magd", "Schmied", "Barde", "Ritter", "Hofnarr", "Königin", "Zauberer", "König"],
 ["Möwe", "Matrose", "Anker", "Kompass", "Kapitän", "Schatzkarte", "Kraken", "Geisterschiff", "Meereskönig"],
 ["Kobold", "Gnom", "Greif", "Kentaur", "Einhorn", "Pegasus", "Hydra", "Phönix", "Urdrache"],
 ["Kupfermünze", "Silberbecher", "Goldbarren", "Rubin", "Smaragd", "Saphir", "Krone", "Zepter", "Diamant"],
 ["Rucksack", "Laterne", "Fernrohr", "Landkarte", "Abenteurerin", "Kletterseil", "Ballon", "Expeditionsschiff", "Verlorene Stadt"],
 ["Kerze", "Zauberbuch", "Kristallkugel", "Zauberstab", "Mondsichel", "Sternschnuppe", "Komet", "Galaxie", "Sternenkrone"],
]
CARDS_EN = [
 ["Farmer", "Maid", "Blacksmith", "Bard", "Knight", "Jester", "Queen", "Wizard", "King"],
 ["Seagull", "Sailor", "Anchor", "Compass", "Captain", "Treasure map", "Kraken", "Ghost ship", "Sea king"],
 ["Goblin", "Gnome", "Griffin", "Centaur", "Unicorn", "Pegasus", "Hydra", "Phoenix", "Elder dragon"],
 ["Copper coin", "Silver goblet", "Gold bar", "Ruby", "Emerald", "Sapphire", "Crown", "Sceptre", "Diamond"],
 ["Backpack", "Lantern", "Telescope", "Map", "Adventurer", "Climbing rope", "Balloon", "Expedition ship", "Lost city"],
 ["Candle", "Spell book", "Crystal ball", "Magic wand", "Crescent moon", "Shooting star", "Comet", "Galaxy", "Star crown"],
]

def esc(t: str) -> str:
    # strings are written already XML/aapt-escaped for &amp; and \'; escape stray quotes/< and apostrophes
    t = t.replace("<", "&lt;")
    out, i = [], 0
    while i < len(t):
        c = t[i]
        if c == "\\" and i + 1 < len(t):
            out.append(t[i:i+2]); i += 2; continue
        if c == "'":
            out.append("\\'")
        elif c == '"':
            out.append('\\"')
        else:
            out.append(c)
        i += 1
    return "".join(out)

def write(folder, lang):
    lines = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by tools/gen_strings.py - do not edit by hand -->", "<resources>"]
    for k, (de, en, other) in S.items():
        v = de if lang == "de" else en if lang == "en" else other.get(lang, en)
        attrs = ' translatable="false"' if k == "app_name" and lang != "de" else ""
        if k == "app_name" and lang != "de":
            continue
        fmt = ' formatted="false"' if ("%" in v and "$" not in v) else ""
        lines.append(f'    <string name="{k}"{fmt}>{esc(v)}</string>')
    def arr(name, items):
        lines.append(f'    <string-array name="{name}">')
        for it in items:
            lines.append(f"        <item>{esc(it)}</item>")
        lines.append("    </string-array>")
    for i in range(30):
        arr(f"buildings_{i}", BUILD_DE[i] if lang == "de" else BUILD_EN[i])
    arr("stage_names", STAGES_DE if lang == "de" else STAGES_EN if lang == "en" else STAGES_X[lang])
    for i in range(6):
        arr(f"card_set_{i}", CARDS_DE[i] if lang == "de" else CARDS_EN[i])
    lines.append("</resources>")
    d = os.path.join(ROOT, folder)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "strings.xml"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

assert all(len(b) == 5 for b in BUILD_DE + BUILD_EN) and len(BUILD_DE) == len(BUILD_EN) == 30
assert all(len(c) == 9 for c in CARDS_DE + CARDS_EN)
for folder, lang in [("values", "de"), ("values-en", "en"), ("values-pl", "pl"), ("values-fr", "fr"), ("values-es", "es")]:
    write(folder, lang)
print("strings:", len(S))
